# Generated by Django 3.0.3 on 2020-02-26 12:27

from django.db import migrations, models
import django.db.models.deletion
import pandemics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to=pandemics.models.get_image_filename, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(max_length=100000)),
                ('head_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_image', to='pandemics.Graphic')),
                ('images', models.ManyToManyField(related_name='images', to='pandemics.Graphic', verbose_name='list of images')),
            ],
        ),
    ]
